# Generated by Django 3.2 on 2021-04-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210416_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Просмотры'),
        ),
    ]
